# Async Management - Exercise 7
In questo esercizio Ã¨ stato volutamente passato un id non valido alla funzione `fetchPersonById`. Implementare il codice necessario per gestire l'eccezione lanciata dalla `Promise`.